print("Hey ik ben Sander hoe heet jij?")
naam = input()
print("Dus je heet " + naam + " Leuk hoe oud ben je?")
leetijd = input()
print("Oke " + naam + " je bent dus " + leetijd + " jaar oud.")
print(naam + " waar woon je?")
plaats = input()
print("Oke " + naam + " je bent dus " + leetijd + " jaar oud en woont in " + plaats)